name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude 'venv' --exclude '.git' . ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/stock-price-prediction/

    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/stock-price-prediction
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart stock-price-prediction
        EOF
